### ISSUE TITLE
[Enhancement Asking] Update ktlint version + override ktlint configuration

### ISSUE THREAD

**Issue by remylavergne** [le0nidas/ktlint-pr-comments#5]
Hi,

First, thank you very much for your **ktlint GitHub Actions** :) It works very well.

But, I have two questions about potentials improvements:

- Is it possible to update ktlint to the last version (0.41) ? [DockerHub image](https://hub.docker.com/layers/le0nidas/ktlint-pr-comments/main/images/sha256-dc61ca474a3190e8b298189fea4f7ca8d64cbcb22d66b50cdde042e170d9a383?context=explore)
- Is it possible to add the possibility to override ktlint configuration with our own config file (host in a specific folder / place into our repository) ?
For example, some rules aren't convenient, like forced indentation with `Missing newline after "="`.

Thank you very much for your time 😄

**Comment by le0nidas** [comment]
Hello Remy,

thank you for taking the time to write this issue.

I just updated the docker image to the latest ktlint version and I also released a new version ([v1.1](https://github.com/le0nidas/ktlint-pr-comments/releases/tag/v1.1)) which supports disabling some rules as described [here](https://github.com/pinterest/ktlint#editorconfig). 

I hope this does the trick for you because I could not find anything for overriding configuration files etc.
